### ISSUE TITLE
explore using letter-spacing to hide text

### ISSUE THREAD

**Issue by siegebell** [siegebell/vsc-prettify-symbols-mode#12]
Example:
```css
hideUglyText {
    letter-spacing: -0.55em;
    font-size: 0.1em;
    visibility: hidden
}
showPrettyText {
    font-size: 10em;
    letter-spacing: normal;
    visibility: visible;
}
```
